services:
  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: default
      DB_URL: jdbc:postgresql://postgres:5432/estudos
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres-study

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=estudos

    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: